#!/bin/sh
DIR=$(dirname $(realpath "$0"))
if [ "$1" = -r ]; then
    shift
    if [ -e "$DIR/jus.so" ]; then
        echo SYSIMAGE: "$DIR/jus.so"
        exec julia -J "$DIR/jus.so" "--project=$DIR" "$DIR/src/rmain.jl" "$@"
    else
        exec julia "--project=$DIR" "$DIR/src/rmain.jl" "$@"
    fi
else
    if [ -e "$DIR/jus.so" ]; then
        echo SYSIMAGE: "$DIR/jus.so"
        exec julia -J "$DIR/jus.so" "--project=$DIR" "$DIR/src/main.jl" "$@"
    else
        exec julia "--project=$DIR" "$DIR/src/main.jl" "$@"
    fi
fi
