#!/bin/sh
DIR=$(dirname $(realpath "$0"))
if [ "$1" = -r ]; then
    shift
    #cd "$DIR"
    exec julia "--project=$DIR" "$DIR/src/rmain.jl" "$@"
else
    exec julia "--project=$DIR" "$DIR/src/main.jl" "$@"
fi
