#!/bin/sh
DIR=$(dirname $(realpath "$0"))
ARGS="--optimize=0 --compile=min"

if [ "$1" = "-v" ]; then
    export JULIA_DEBUG=all
fi
if [ -e "$DIR/jus.so" ]; then
    echo SYSIMAGE: "$DIR/jus.so"
    exec julia $ARGS -J "$DIR/jus.so" "--project=$DIR" "$DIR/test/test.jl"
else
    exec julia $ARGS "--project=$DIR" "$DIR/test/test.jl"
fi
