#!/bin/sh
DIR=$(dirname $(realpath "$0"))
if [ "$1" = "-v" ]; then
    export JULIA_DEBUG=Jus
fi
if [ -e "$DIR/jus.so" ]; then
    echo SYSIMAGE: "$DIR/jus.so"
    exec julia -O 0 -J "$DIR/jus.so" "--project=$DIR" "$DIR/test/test.jl"
else
    exec julia "--project=$DIR" "$DIR/test/test.jl"
fi
